trigger: none

parameters:
  - name: agentPool
    type: string
    default: 'ubuntu-latest'
  - name: agent
    type: string
    default: 'default'
  - name: appName
    type: string
    default: 'default'
  - name: azureSubscription
    type: string
    default: 'Azure subscription 1 (27589ab3-7c64-4fdc-a2f4-16e995178402)'
  - name: CRON_API_URL
    type: string
    default: 'default'
  - name: DB_HOST
    type: string
    default: 'default'
  - name: DB_PASS
    type: string
    default: 'default'
  - name: DB_USER
    type: string
    default: 'default'
  - name: DEV_DB_HOST
    type: string
    default: 'default'
  - name: DEV_DB_PASS
    type: string
    default: 'default'
  - name: DEV_DB_USER
    type: string
    default: 'default'
  - name: NODE_HOST
    type: string
    default: 'default'
  - name: ROUTING_APIKEY
    type: string
    default: 'default'
  - name: SWAGGER_STATS_PASSWORD
    type: string
    default: 'default'
  - name: SWAGGER_STATS_USERNAME
    type: string
    default: 'default'
  - name: COMPANY_DB
    type: string
    default: 'default'
  - name: NODE_ENV
    type: string
    default: 'production'

variables:
  # Azure Resource Manager connection
  _azureSub: ${{ parameters.azureSubscription }}
  _agentPool: ${{ parameters.agentPool }}
  _agent: ${{ parameters.agent }}
  

stages:

- stage: DeployAndConfigure
  displayName: Deploy And Configure
  jobs:
  - job: Deploy
    displayName: Deploy And Configure
    pool:
      name: $(_agentPool)
      demands:
      - agent.name -equals $(_agent)

    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '12.x'
    
    - script: |
        npm install 
      displayName: 'Install node_modules'

    - task: ArchiveFiles@2
      displayName: 'Zip Source Code'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy, Set Env, and Move config folders' 
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(_azureSub)'
        appType: 'webApp'
        WebAppName: '${{ parameters.appName }}'
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        enableCustomDeployment: true
        DeploymentType: 'zipDeploy'
        RemoveAdditionalFilesFlag: true
        AppSettings: '-NODE_ENV production -CRON_API_URL ${{parameters.CRON_API_URL }} -DB_HOST ${{ parameters.DB_HOST }} -DB_PASS ${{ parameters.DB_PASS }} -DB_USER ${{ parameters.DB_USER }} -DEV_DB_HOST ${{ parameters.DEV_DB_HOST }} -DEV_DB_PASS ${{ parameters.DEV_DB_PASS }} -DEV_DB_USER ${{ parameters.DEV_DB_USER }} -NODE_HOST ${{ parameters.NODE_HOST }} -ROUTING_APIKEY ${{ parameters.ROUTING_APIKEY }}  -SWAGGER_STATS_PASSWORD ${{ parameters.SWAGGER_STATS_PASSWORD }} -SWAGGER_STATS_USERNAME ${{ parameters.SWAGGER_STATS_USERNAME }} -COMPANY_DB ${{ parameters.COMPANY_DB }} '
        ScriptType: 'File Path'
        ScriptPath: '$(System.DefaultWorkingDirectory)/post_install_script.bat'
